name: PROD

on:
  workflow_dispatch:

jobs:
  prod:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Git clone
        run: git clone git@github.com:TooMuchRuss1a/imctech-laravel.git
      - name: PHP install
        uses: shivammathur/setup-php@v2
        with:
          php-version: "latest"
      - name: Composer install
        uses: ramsey/composer-install@v2
        with:
          working-directory: /home/runner/work/imctech-laravel/imctech-laravel/imctech-laravel/
          composer-options: "--no-dev"
      - name: Deploy with rsync
        run: rsync -avz /home/runner/work/imctech-laravel/imctech-laravel/imctech-laravel/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/${{ secrets.SSH_USER }}/data/www/imctech.ru
      - name: Migrating
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script_stop: true
          script: |
            cd www/imctech.ru/
            php artisan migrate
            exit
