name: Test

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script_stop: true
          script: |
            rsync -avz git@github.com:TooMuchRuss1a/imctech-laravel.git www/dev.imctech.ru/
            cd www/dev.imctech.ru/
            php artisan migrate
            php artisan test
            exit
